export const dataSource: object[] = [
  {
    id: "GBS-450078",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(1).webp",
    name: "Vinu Kuttan",
    jobTitle: "SDE-1",
    place: "Trivandrum",
  },
  {
    id: "IND-123456",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(10).webp",
    name: "Rahul Sharma",
    jobTitle: "Software Engineer",
    place: "Mumbai",
  },
  {
    id: "IND-789012",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(11).webp",
    name: "Aisha Patel",
    jobTitle: "Frontend Developer",
    place: "Bangalore",
  },
  {
    id: "IND-345678",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(12).webp",
    name: "Sneha Gupta",
    jobTitle: "UI Designer",
    place: "Delhi",
  },
  {
    id: "IND-901234",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(13).webp",
    name: "Amit Singh",
    jobTitle: "Full Stack Developer",
    place: "Hyderabad",
  },
  {
    id: "IND-567890",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(2).webp",
    name: "Neha Kumar",
    jobTitle: "Data Analyst",
    place: "Chennai",
  },
  {
    id: "IND-111213",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(3).webp",
    name: "Kiran Reddy",
    jobTitle: "Product Manager",
    place: "Pune",
  },
  {
    id: "IND-141516",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(4).webp",
    name: "Priya Gupta",
    jobTitle: "Software Developer",
    place: "Kolkata",
  },
  {
    id: "IND-171819",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(5).webp",
    name: "Rohit Verma",
    jobTitle: "QA Engineer",
    place: "Ahmedabad",
  },
  {
    id: "IND-202122",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(6).webp",
    name: "Anjali Sharma",
    jobTitle: "DevOps Engineer",
    place: "Jaipur",
  },
  {
    id: "IND-232425",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(7).webp",
    name: "Vivek Patel",
    jobTitle: "Backend Developer",
    place: "Surat",
  },
  {
    id: "IND-262728",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(8).webp",
    name: "Pooja Singh",
    jobTitle: "UX Designer",
    place: "Lucknow",
  },
  {
    id: "IND-293031",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(9).webp",
    name: "Akash Gupta",
    jobTitle: "Software Engineer",
    place: "Indore",
  },
  {
    id: "IND-323334",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280.webp",
    name: "Meera Reddy",
    jobTitle: "Frontend Developer",
    place: "Visakhapatnam",
  },
  {
    id: "IND-353637",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(8).webp",
    name: "Rajesh Kumar",
    jobTitle: "Data Scientist",
    place: "Nagpur",
  },
  {
    id: "IND-383940",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(1).webp",
    name: "Divya Sharma",
    jobTitle: "Full Stack Developer",
    place: "Bhopal",
  },
  {
    id: "IND-414243",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(11).webp",
    name: "Vikram Singh",
    jobTitle: "Software Developer",
    place: "Coimbatore",
  },
  {
    id: "IND-444546",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(5).webp",
    name: "Jyoti Patel",
    jobTitle: "UI/UX Designer",
    place: "Kochi",
  },
  {
    id: "IND-474849",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(6).webp",
    name: "Arjun Gupta",
    jobTitle: "Backend Developer",
    place: "Patna",
  },
  {
    id: "IND-505152",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(7).webp",
    name: "Priyanka Reddy",
    jobTitle: "QA Engineer",
    place: "Guwahati",
  },
  {
    id: "IND-535455",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(1).webp",
    name: "Ravi Verma",
    jobTitle: "DevOps Engineer",
    place: "Thiruvananthapuram",
  },
  {
    id: "IND-565758",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(12).webp",
    name: "Ananya Sharma",
    jobTitle: "Frontend Developer",
    place: "Bhubaneswar",
  },
  {
    id: "IND-596061",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(11).webp",
    name: "Suresh Kumar",
    jobTitle: "Software Engineer",
    place: "Amritsar",
  },
  {
    id: "IND-626364",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(8).webp",
    name: "Deepika Singh",
    jobTitle: "UI/UX Designer",
    place: "Ajmer",
  },
  {
    id: "IND-656667",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(1).webp",
    name: "Arun Kumar",
    jobTitle: "Data Scientist",
    place: "Varanasi",
  },
  {
    id: "IND-686970",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(12).webp",
    name: "Neha Verma",
    jobTitle: "Backend Developer",
    place: "Agra",
  },
  {
    id: "IND-717273",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(6).webp",
    name: "Rajat Sharma",
    jobTitle: "Full Stack Developer",
    place: "Allahabad",
  },
  {
    id: "IND-747576",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(7).webp",
    name: "Aditi Patel",
    jobTitle: "Software Developer",
    place: "Patiala",
  },
  {
    id: "IND-777879",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(12).webp",
    name: "Sanjay Gupta",
    jobTitle: "UI/UX Designer",
    place: "Ludhiana",
  },
  {
    id: "IND-808182",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(1).webp",
    name: "Anita Sharma",
    jobTitle: "Backend Developer",
    place: "Faridabad",
  },
  {
    id: "IND-838485",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(10).webp",
    name: "Vijay Kumar",
    jobTitle: "QA Engineer",
    place: "Gurgaon",
  },
  {
    id: "IND-868788",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(11).webp",
    name: "Ritu Verma",
    jobTitle: "DevOps Engineer",
    place: "Noida",
  },
  {
    id: "IND-899091",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(12).webp",
    name: "Rahul Kumar",
    jobTitle: "Frontend Developer",
    place: "Chandigarh",
  },
  {
    id: "IND-929394",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(8).webp",
    name: "Anjali Gupta",
    jobTitle: "Software Engineer",
    place: "Jodhpur",
  },
  {
    id: "IND-959697",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(5).webp",
    name: "Nitin Sharma",
    jobTitle: "Data Scientist",
    place: "Kota",
  },
  {
    id: "IND-9899100",
    imgUrl: "https://raw.githubusercontent.com/ananduremanan/Demo/main/Avatars/avatar-4623511_1280%20(6).webp",
    name: "Preeti Verma",
    jobTitle: "Full Stack Developer",
    place: "Udaipur",
  },
];
